/*
 * Statflo API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.statflo.client.api;

import com.statflo.client.model.AccountCredential;
import com.statflo.client.model.AccountCredentialCreate;
import com.statflo.client.model.AccountCredentialPaginationResponse;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for AccountCredentialsApi
 */
@Ignore
public class AccountCredentialsApiTest {

    private final AccountCredentialsApi api = new AccountCredentialsApi();

    /**
     * 
     *
     * Create a account credential.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void accountCredentialCreateTest() throws Exception {
        AccountCredentialCreate body = null;
        AccountCredential response = api.accountCredentialCreate(body);

        // TODO: test validations
    }
    /**
     * 
     *
     * Retrieve a account credential.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void accountCredentialGetTest() throws Exception {
        String id = null;
        AccountCredential response = api.accountCredentialGet(id);

        // TODO: test validations
    }
    /**
     * 
     *
     * Search account credentials.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void accountCredentialSearchTest() throws Exception {
        java.util.HashMap filter = null;
        String query = null;
        Integer page = null;
        Integer perPage = null;
        String sort = null;
        AccountCredentialPaginationResponse response = api.accountCredentialSearch(filter, query, page, perPage, sort);

        // TODO: test validations
    }
    /**
     * 
     *
     * Update a account credential.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void accountCredentialUpdateTest() throws Exception {
        String id = null;
        AccountCredential body = null;
        AccountCredential response = api.accountCredentialUpdate(id, body);

        // TODO: test validations
    }
}
