/*
 * Statflo API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.statflo.client.api;

import com.statflo.client.ApiException;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for WidgetsApi
 */
@Ignore
public class WidgetsApiTest {

    private final WidgetsApi api = new WidgetsApi();

    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void v4ApiWidgetsCampaignsAccountIdGetTest() throws ApiException {
        String accountId = null;
        api.v4ApiWidgetsCampaignsAccountIdGet(accountId);

        // TODO: test validations
    }
}
