name: Tedt codegen

on:
  workflow_dispatch:
    inputs:
      GIT_REF:
        description: Git Ref (Optional)    
        required: false 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Create Containers
        run: ls -la


